:icons: font

= ac-fe-intellij-plugin

== Usage

Download the `.jar` file (see _Releases_ tab) and place it in your IntelliJ
IDEA user directory at `$IDEA_USERDIR/config/plugins`.
During the next startup of IntelliJ it should be automatically added to your list
of installed plugins.

Note: Your IntelliJ IDEA version must be >= 2019.3

== Development

=== Prerequisites

* Installation of JetBrains' GrammarKit Plugin. This is required so that you can generate code from `.flex` and `.bnf` files.

=== Backlog
* Syntax Highlighting for following tokens (partly taken from Eclipse plugin)
  ** Annotation
  ** Built-in functions
  *** insert
  *** lsearch
  *** price_field
  *** print
  *** ts
  *** min
  ** Built-in variables
  *** $FIELDS
  *** $SYMBOL
  *** $TREEID
  ** Single Line Comment icon:check-circle[]
  ** Block Comment
  ** Cross reference
  ** Data type icon:check-circle[]
  ** Default
  ** Deprecated final variable
  ** Deprecated function
  ** Deprecated global
  ** Doc comment
  ** Final variable
  ** Global variable icon:check-circle[]
  ** Invalid Symbol
  ** Keyword icon:check-circle[]
  ** Local variable
  ** Number
  ** Punctuation character
  ** Special variable
  ** String icon:check-circle[]
  ** Task Tag
  ** method references in function argument icon:check-circle[]
* Auto Completion
* Reference Resolution and jumping to definition
* Brace Pair Highlighting icon:check-circle[]
* Toggle Regions / Region Folding
* TODO Detection
* Display _Jump-To_ icons on the left hand side of the editor to show where the function is reference (e.g. in _co(HASH)RULES.tsv_ file)
* dead code analysis (requires cross reference checks in at least _co(HASH)RULES.tsv_ file)

=== Local Testing

. Run the gradle task _runIde_ of the intellij gradle plugins
. Open files with FE syntax in newly opened IntelliJ Community Edition instance

=== Sources

* https://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support.html
* https://medium.com/@shan1024/custom-language-plugin-development-for-intellij-idea-part-02-f948a078dc81
* https://medium.com/@shan1024/custom-language-plugin-development-for-intellij-idea-part-03-2bfcc7f1517
* https://medium.com/@shan1024/custom-language-plugin-development-for-intellij-idea-part-04-df2f3ce88b30
* https://github.com/Shan1024/Simple-Intellij-Plugin/blob/master/src/main/java/org/shan/grammar/Simple.flex
* https://github.com/JetBrains/Grammar-Kit/blob/master/TUTORIAL.md


== Stubs


* Define an interface for the stub, derived from the StubElement interface (example).
  => FunctionDefinitionStub
* Provide an implementation for the interface (example).
  => FunctionDefinitionStubImpl
* Make sure that the interface for the PSI element extends StubBasedPsiElement parameterized by the type of the stub interface (example).
  => generated FormulaEngineFunctionDefinition
* Make sure that the implementation class for the PSI element extends StubBasedPsiElementBase parameterized by the type of the stub interface (example). Provide both a constructor that accepts an ASTNode and a constructor which accepts a stub.
  => generated FormulaEngineFunctionDefinitionImpl
* Create a class which implements IStubElementType and is parameterized with the stub interface and the actual PSI element interface (example). Implement the createPsi() and createStub() methods for creating PSI from a stub and vice versa. Implement the serialize() and deserialize() methods for storing the data in a binary stream.
  => FunctionDefinitionElementType (via ElementTypeBase)
* Use the class implementing IStubElementType as the element type constant when parsing (example).
* Make sure that all methods in the PSI element interface access the stub data rather than the PSI tree when appropriate (example: Property.getKey() implementation).
